### ISSUE TITLE
Make reference to our repository in the documents page

### ISSUE THREAD

**Issue by esfoliante** [Nucleo-Estudantes-Informatica-ISEP/antirecurso#10]
In this issue we want:
- Your beautiful soul to create a reference to this repository in the documents page

**Comment by sachin-barse** [comment]
Hi,
I want to contribute to this project by fixing this issue. Still, when I push my changes, I get the error "Permission to Nucleo-Estudantes-Informatica-ISEP/antirecurso.git denied" fatal: Could not read from remote repository. This will be my first contribution to any open-source project, Pls help me to understand if I am missing something here.

**Comment by esfoliante** [comment]
> 

Hello Sachin!
Thank you, in advance, for your interest in helping us with this project!

Yes, there was a little problem with the repository but now you should be able to push your changes into your new branch, once you accept the invite in your github email (barse.sachin@yahoo.com).
Remember to follow the rules stated in the contributions section of the REAME.md document.

Once again thank you and we're looking forward to reviewing your code!

**Comment by sachin-barse** [comment]
Hi Miguel,

Thanks a lot for allowing me to contribute on this project, Created [PR ](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/pull/14)for this issue kindly review and let me know if this is what expected.
