### ISSUE TITLE
I have some legacy NEI event sites, are y'all interested in them?

### ISSUE THREAD

**Issue by LuchoTurtle** [Nucleo-Estudantes-Informatica-ISEP/antirecurso#39]
I've opened an issue but got no response (perhaps you don't have notifications enabled for it) in https://github.com/Nucleo-Estudantes-Informatica-ISEP/.github/issues/1.

Figured I'd open the issue here, as well!

Props on setting up NEI's own organization on Github and expanding [Nucleo-Estudantes-Informatica-ISEP/antirecurso](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso), it was sorely needed!

I was an old member a few years back and I have a private repo with some code from past events. Would y'all be interested in them? If so, invite me to the org or something, and I'll transfer the repo to your org so you can do whatever you want with it 😄 (even if it's just to be archived and for historical reasons).

Here's the repo -> [LuchoTurtle/nei-stuff](https://github.com/LuchoTurtle/nei-stuff)

**Comment by ricardo177m** [comment]
Hey! Thank you for reaching out. I'm glad to hear that you find Anti Recurso's expansion valuable!

Although I don't coordinate such matters, I will make sure the relevant individuals within the organization get in touch with you.

**Comment by Eduardoooxd** [comment]
Hey @LuchoTurtle 🎉, 
I'm glad that you reach out to us.

We would be glad to have old code for historical reasons and also open sourcing as well on our organization.
I already invited you with member role, ensuring that you have permissions to create repos in the organization.

For security reasons, I have to revoke this role after you transfer the repo.

If you need help with permissions or anything else, feel free to PM.

**Comment by LuchoTurtle** [comment]
Cheers @Eduardoooxd 

I've transferred the repo, it's yours - https://github.com/Nucleo-Estudantes-Informatica-ISEP/old-events.

Feel free to revoke the role now :)

**Comment by Eduardoooxd** [comment]
Thanks for the code @LuchoTurtle 

Hit us up if you need some future or want to collaborate with us in the future.

Cheers 🎉
