### ISSUE TITLE
Fix exam pagination in some browsers

### ISSUE THREAD

**Issue by tomasflopes** [Nucleo-Estudantes-Informatica-ISEP/antirecurso#41]
![image](https://github.com/Nucleo-Estudantes-Informatica-ISEP/antirecurso/assets/50304854/d5282135-1291-4dab-ba46-96597ab5293e)

The pagination feature at the end of the page is not functioning as expected in certain browsers. When users click on the pagination links, they are redirected to the main page instead of navigating to the desired page. This behavior is intended in case of an error occurrence.

The issue is likely related to some browser's politics that [block mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content) and are not allowing the request to be fulfilled dynamically. It is possible that the problem lies in the backend, but further investigation is needed to determine the exact cause.

Due to time constraints, I haven't been able to delve deeper into this matter. I encourage you to thoroughly investigate the issue, considering both frontend and backend aspects, in order to find a solution.

**Comment by ricardo177m** [comment]
Fixed in the backend.
