### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by tomasflopes** [Nucleo-Estudantes-Informatica-ISEP/antirecurso#47]
The current readme of our open-source project is informative and well-structured. However, the technologies section should be rewritten to reflect the current tech stack, specifically highlighting Next 13 as the framework of choice. Outdated references to ~~good~~ old PHP and Laravel days should be removed, and new information about the technologies used in the project should be added.

Furthermore, we believe that a general overhaul of the entire document is necessary to improve its overall quality. This includes tidying up the existing content and incorporating additional relevant information as deemed appropriate. By enhancing the documentation, we can provide better guidance to users, contributors, and maintainers, and ensure that the project remains up-to-date and accessible.

### Expected Changes:

- Document Overhaul: The entire documentation should be reviewed and improved to enhance its clarity, organization, and relevance. This involves:
  - Tidying up existing content: Removing any outdated or redundant information, reorganizing sections for better flow, and ensuring consistency in terminology and formatting.
  - Addition of relevant information: Identifying any missing information or gaps in the documentation and incorporating new content to address those areas. This could include additional installation instructions, configuration details and usage examples.
  - Writing examples and code snippets: Writing some code examples or snippets throughout the documentation to ensure that a new developer can be easily integrated with the team.

**Comment by MiguelOliveira1200874** [comment]
@ricardo177m Added the Contact Us Section and corrected what you asked for. 

PS : Please check the email i sent you on support.antirecurso@nei-isep.org.
